---
title: "COVID-19 Srbija - Statistika "
author: "Podaci preuzeti sa sajta data.gov.rs i covid19.rs za dan"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
date: '`r format(Sys.Date(),"%d. %m. %Y.")`'

---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(readxl)
library(tidyverse)
library(writexl)
library(httr)
library(plotly)
library(crosstalk)
library(rvest)


#nova updateoana lista 14. april

url2<-"https://data.gov.rs/s/resources/covid-19-zarazheni/20200414-163734/covid-19.xls"
GET(url2, write_disk(tf <- tempfile(fileext = ".xls")))
covidserbianew <- read_excel(tf)
str(covidserbianew)

covidserbianew$Пол <- stringi::stri_trans_general(covidserbianew$Пол, "Serbian-Latin/BGN")
covidserbianew$`Општина (МУП)` <- stringi::stri_trans_general(covidserbianew$`Општина (МУП)`, "Serbian-Latin/BGN")
covidserbianew$`Место (МУП)` <- stringi::stri_trans_general(covidserbianew$`Место (МУП)`, "Serbian-Latin/BGN")

covidserbianew<-covidserbianew%>%
  rename(Pol = Пол)%>%
  rename(NazivTeritorije =`Општина (МУП)`)%>%
  rename(`Mesto(MUP)`=`Место (МУП)`)

  covidserbianew<-covidserbianew%>% 
  mutate(Datum=Sys.Date()-1)%>%
    drop_na(NazivTeritorije)





covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="SAVSKI VENAC"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="VOŽDOVAC"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="GROCKA"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="VRAČAR"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="PALILULA"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="NOVI BEOGRAD"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="ČUKARICA"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="ZVEZDARA"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="STARI GRAD"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="RAKOVICA"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="ZEMUN"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="SURČIN"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="SOPOT"]="BEOGRAD"
covidserbianew$NazivTeritorije[covidserbianew$NazivTeritorije=="BARAJEVO"]="BEOGRAD"

covidserbia14.apr<-covidserbianew%>%
  group_by(`NazivTeritorije`)%>%
  count(NazivTeritorije)





#importing longitude and latitude
municipalitiescsv<-read_csv("longlatcitiesserb.csv",col_names = TRUE)







covidserbialonglat1<-left_join(covidserbia14.apr,municipalitiescsv,by="NazivTeritorije")
duplicated(covidserbialonglat1)
covidserbialonglat1<- covidserbialonglat1[!duplicated(covidserbialonglat1), ]

#cicevac
covidserbialonglat1[24,3]<-21.4437
covidserbialonglat1[24,4]<-43.7213
#curoija

covidserbialonglat1[26,3]<-21.3748
covidserbialonglat1[26,4]<-43.9255
#leposavic
covidserbialonglat1[61,3]<-20.8011
covidserbialonglat1[61,4]<-43.1016

#niska banja
covidserbialonglat1[72,3]<-22.0044
covidserbialonglat1[72,4]<-43.2982
#obilic
covidserbialonglat1[79,3]<-21.0670
covidserbialonglat1[79,4]<-42.6869
#Paracin
covidserbialonglat1[84,3]<-21.4039
covidserbialonglat1[84,4]<-43.8586
#pec
covidserbialonglat1[85,3]<-20.2887
covidserbialonglat1[85,4]<-42.6593

#pecinci
covidserbialonglat1[86,3]<-19.9697
covidserbialonglat1[86,4]<-44.9047




#scraping number of dead

my_html<-read_html("https://covid19.rs/%d1%81%d1%82%d0%b0%d1%82%d0%b8%d1%81%d1%82%d0%b8%d1%87%d0%ba%d0%b8-%d0%bf%d0%be%d0%b4%d0%b0%d1%86%d0%b8-%d0%be-%d0%ba%d0%be%d1%80%d0%be%d0%bd%d0%b0%d0%b2%d0%b8%d1%80%d1%83%d1%81%d1%83/")
scrapingdead<-my_html%>%html_nodes("p")%>%html_text

scrapingdead[which(scrapingdead=="БРОЈ ПРЕМИНУЛИХ")+3]




#zarazeni testirani

zarazenitestirani<-read.csv("zarazenitestirani.csv")
zarazenitestirani$Datum<-as.Date( zarazenitestirani$Datum)

sum(zarazenitestirani$BrojZarazenih)



```


Row {data-height=185} 
----------------------------------------------------------------

### **Ukupan broj zaraženih**
```{r}
#creation of value box in upper left corner

valueBox(format(scrapingdead[which(scrapingdead=="УКУПАН БРОЈ ОБОЛЕЛИХ")+1],big.mark = ","),color = "#B22222")


```


### **Ukupan broj izlečenih**
```{r}

valueBox("preko 400",color = "green")#,href="http://rs.n1info.com/Vesti/a582261/Koronavirus-u-Srbiji-Interaktivni-grafikoni-sa-brojem-zarazenih-po-gradovima.html")
```

### **Ukupan broj preminulih**
```{r}

valueBox(format(scrapingdead[which(scrapingdead=="БРОЈ ПРЕМИНУЛИХ")+3], big.mark = ","),color = "black")
```


Row {data-height=815} 
-----------------------------------------------------------------------
### **Mapa sa ukupnim brojem zaraženih po opštinama na dan 14.04.**

```{r}


m<-leaflet(covidserbialonglat1) %>% 
  addTiles(attribution = paste(
    "&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors","Podaci preuzeti sa: <a href=\"https://data.gov.rs/sr/datasets/covid-19-zarazheni/\">data.gov.rs</a>","Kontakt za dashboard:<a href=\"mailto:etijana@gmail.com\">Tijana Blagojev </a"))%>%
  setView(lng = 21.0059, lat = 44.0165, zoom = 7)%>%
  addCircles(radius = ~`n`^(.5)*500,weight = 1, color = "black",
             fillColor = "red", fillOpacity = 0.6,  
             popup = ~paste("Opština:", `NazivTeritorije`, "<br>","Broj slučajeva:",`n`, "<br>"))

#addAwesomeMarkers( icon = icon2, popup = ~paste(
# "Grad:", `NazivTeritorije`, "<br>","Broj slučajeva:",`sum(Vrednost)`, "<br>"))

m
```


### **Broj testiranih i broj pozitivnih u Srbiji po danima**

```{r}
gg <- ggplot(zarazenitestirani) +
  geom_area(aes(Datum, `BrojTestiranih`,fill="Testirani"))+
  geom_area(aes(Datum,`BrojZarazenih`,fill= "Pozitivni"))+
 scale_fill_manual(values =  c("#B22222","#4169E1"))+
  scale_x_date(date_breaks = "1 week",date_labels = "%d.%m.")+
  ylab("")+
  xlab("")+
  theme(
        legend.title = element_blank(),
        panel.background = element_blank(),
       plot.margin = margin(0, 0, 2.2, 0, "cm"),
        plot.caption = element_text()
  )



  ggplotly( gg) %>%
  layout(legend = list(
      orientation = "h"), annotations = 
 list(x = 1, y = -0.3, text = "Podaci preuzeti sa: <a href=\"https://covid19.rs/статистички-подаци-о-коронавирусу/\">covid19.rs</a>", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=9)))

```

